services:
  tinyfilemanager:
    build: . 
#    image: tinyfilemanager/tinyfilemanager                    ###  If you want to run a Docker container on an image from Docker Hub, comment on the upper line 'build: .'
    container_name: tinyfilemanager
    restart: always
    ports:
      - "80:80"
    volumes:
      - /absolute/path/to/storage/data:/var/www/html/data      ### Add to commend or remove this line and uncomment the last lines if you want to use Docker volumes for stored data. 
      - /absolute/path/to/config.php:/var/www/html/config.php  ### Uncomment if you are using config.php
#      - tinyfilenabager_data:/var/www/html/data               ### uncomment if you want to use docker volumes as storage data. 

# volumes:
#    tinyfilenabager_data: