services:
  tinyfilemanager:
    build: . 
#    image: tinyfilemanager/tinyfilemanager                    ### if you want to run docker conatiner on image from dockerhub and commant upper line 'build: .'
    container_name: tinyfilemanager
    restart: always
    ports:
      - "80:80"
    volumes:
      - /absolute/path/to/storage/data:/var/www/html/data      ### add to commend or remove this line and uncommend last lines if you want to use docker volues for stored data. 
      - /absolute/path/to/config.php:/var/www/html/config.php  ### if you using config.php
#      - tinyfilenabager_data:/var/www/html/data               ### uncommend if you want to use docker volumes as storage data 

# volumes:
#    tinyfilenabager_data: